export const GET_HEALTH_NEWS_REQUEST = "GET_HEALTH_NEWS_REQUEST";
export const GET_HEALTH_NEWS_SUCCESS = "GET_HEALTH_NEWS_SUCCESS";
export const GET_HEALTH_NEWS_FAILURE = "GET_HEALTH_NEWS_FAILURE";

export const GET_ADS_REQUEST = "GET_ADS_REQUEST";
export const GET_ADS_SUCCESS = "GET_ADS_SUCCESS";
export const GET_ADS_FAILURE = "GET_ADS_FAILURE";

